spring.application.name=danko-stream
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/DankoStream}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Letsdoit!}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

rapidapi.moviesdatabase.base-url=https://moviesdatabase.p.rapidapi.com
rapidapi.moviesdatabase.host=moviesdatabase.p.rapidapi.com
rapidapi.moviesdatabase.key=${RAPIDAPI_KEY:1487547297msh68b44c2168d3246p1d8f3djsne7babdf3cb2c}
