spring.application.name=java-payfast
server.port=8080

# PayFast Configuration
payfast.merchant-id=10034560
payfast.merchant-key=7ihweq67use4r
payfast.passphrase=devlinkpayfast
payfast.sandbox=true
payfast.sandbox-url=https://sandbox.payfast.co.za/eng/process
payfast.live-url=https://www.payfast.co.za/eng/process
payfast.return-url=http://localhost:4200/payment/success
payfast.cancel-url=http://localhost:4200/payment/cancel
payfast.notify-url=https://nonrepresentable-nakesha-unnumerous.ngrok-free.dev/api/payments/notify
