spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/DevLink
spring.datasource.username=postgres
spring.datasource.password=Letsdoit!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=bntEBqpJYmqS/xo/UGgbIsjw7Run+ZWy/wj5D5iipi0=
app.jwt.expiration-ms=86400000
